--CREATE TABLE categorias(
--        id uuid not null,
--        name varchar(255),
--        primary key (id)
--);
--CREATE TABLE profiles(
--        is_present boolean not null,
--        id uuid not null,
--        document varchar(255),
--        lastname varchar(255),
--        name varchar(255),
--        primary key (id)
--);
--
--CREATE TABLE tickets(
--        create_date timestamp(6),
--        id uuid not null,
--        meta varchar(255),
--        primary key (id)
--);
--
--CREATE TABLE tickets_category(
--    category_id uuid not null unique,
--    ticket_entity_id uuid not null
--);
--
--CREATE TABLE users(
--        id uuid not null,
--        profile_id uuid unique,
--        email varchar(255) unique,
--        password varchar(255),
--        primary key (id)
--);
--
--alter table if exists tickets_category
--       add constraint FKrp9bfedkhkyaqjtode8434ip5
--       foreign key (category_id)
--       references categorias;
--
--
--alter table if exists tickets_category
--       add constraint FKmhy5u7tysn1eo3j52je03b6ku
--       foreign key (ticket_entity_id)
--       references tickets;
--
--alter table if exists users
--       add constraint FKq2e6rj0p6p1gec2cslmaxugw1
--       foreign key (profile_id)
--       references profiles;